---
version: "3.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1510
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    volumes:
      - /docker/qbittorrent-config:/config
      - /data/torrents:/data/torrents/
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1520
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /docker/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1530
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /docker/radarr-config:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1540
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /docker/sonarr-config:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1550
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /docker/readarr-config:/config
      - /data:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1560
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /docker/lidarr-config:/config
      - /data:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1570
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /docker/jellyfin-config:/config
      - /data/media:/data
    ports:
      - 8096:8096
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1580
      - PGID=1500
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /docker/jellyseerr-config:/app/config
    ports:
      - 5056:5055
    restart: unless-stopped\n
