---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /path/to/data:/media/config/prowlarr-config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /path/to/data:/media/config/radarr-config
      - /path/to/movies:/media/torrents/movies #optional
      - /path/to/downloadclient-downloads:/media/torrents/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /path/to/data:/media/config/sonarr-config
      - /path/to/tvseries:/media/torrents/tv-series #optional
      - /path/to/downloadclient-downloads:/media/torrents/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /path/to/data:/media/config/readarr-config
      - /path/to/books:/media/torrents/books #optional
      - /path/to/downloadclient-downloads:/media/torrents/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
 
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /path/to/appdata/config:/media/config/lidarr-config
      - /path/to/music:/media/torrents/music #optional
      - /path/to/downloads:/media/torrents/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    volumes:
      - /path/to/appdata/config:/media/config/qbittorrent-config
      - /path/to/downloads:/media/torrents/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
